ParkLot/ParkLot/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('index.urls', namespace='index')),
    url(r'^map/', include('maps.urls', namespace='maps')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^users/', include('users.urls', namespace='users')),
]

ParkLot/index/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.indexView, name='index'),
]

ParkLot/maps/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.gmapView, name='gmap'),
    url(r'^new_spot/$', views.new_spot, name='new_spot'),
    # url(r'^new_order/$', views.createOrder, name='new_order')
]

ParkLot/order/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # まだお客さんのIDは確認させないので、
    url(r'^$', views.orderView, name='my_order')
]

ParkLot/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views
urlpatterns = [
    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', views.logoutView, name='logout'),
    url(r'^register/$', views.registerView, name='register'),
]

ParkLot/index/models.py
from django.db import models

ParkLot/maps/models.py
from django.db import models
from django.contrib.auth.models import User

class Lot(models.Model):
    id = models.AutoField(primary_key=True)
    # 0 for Indoor; 1 for Outdoor;
    type = models.BooleanField('IO')
    longitude = models.FloatField('Longitude')
    latitude = models.FloatField('Latitude')
    nums = models.IntegerField('spots')
    idle = models.IntegerField('idle')

class Spot(models.Model):
    """Spot"""
    # txt = models.CharField(max_length=50)
    # def __str__(self):
    #     """return str(Spot)"""
    #     return self.txt
    id = models.AutoField(primary_key=True)
    belong = models.ForeignKey(Lot)
    longitude = models.FloatField('Longitude')
    latitude = models.FloatField('Latitude')
    busy = models.BooleanField('used', default=False)
    key = models.CharField('key', max_length=50)
    personal = models.BooleanField('personal', default=False)
    # after user login
    owner = models.ForeignKey(User, default=False)
    # type private or public
    # private -- belong to someone

ParkLot/order/models.py
from django.db import models
from maps.models import Spot, Lot

class Order(models.Model):
    id = models.AutoField(primary_key=True)
    spot = models.ForeignKey(Spot)
    # user = models.ForeignKey(User)
    # active when True
    active = models.BooleanField(default=True)
    # auto_now_add constraint
    startTime = models.DateTimeField(auto_now_add=True)
    # auto_now time during alter
    stopTime = models.DateTimeField(auto_now=True)

ParkLot/users/models.py
from django.db import models

# Create your models here.

ParkLot/maps/forms.py
from django import forms
from .models import *
# release
from order.models import Order
# Coding
# from ..order.models import Order
class SpotForm(forms.ModelForm):
    class Meta:
        model = Spot
        fields = ['latitude', 'longitude', 'personal']  # busy_invalid id_auto
        labels = {'latitude': '', 'longitude': ''}
        # longitude = forms.FloatField(labels='longitude')
        # latitude = forms.FloatField(labels='latitude')

class orderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['spot']
        labels = {'spot': ''}

ParkLot/order/forms.py
from django import forms
from .models import *

class orderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = []
        labels = []

ParkLot/index/views.py
from django.shortcuts import render
def indexView(request):
    """Main Page"""
    return render(request, 'index.html')

ParkLot/maps/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse  # nani kore>?
from .models import Spot, Lot
import json
from .forms import SpotForm, orderForm
# release
from order.models import Order
# coding
# from ParkLot.order.models import Order
from django.contrib.auth.decorators import login_required
from .models import Spot

def gmapView(request):
    center = [108.910462, 34.245147]
    return render(request, 'gmap.html', {
        'Center': json.dumps(center)
    })

@login_required
def new_spot(request):
    if request.method != 'POST':
        form = SpotForm()
    else:
        # POST
        form = SpotForm(request.POST)
        if form.is_valid():
            form.personal = True
            form.save()  # data_save
            return HttpResponseRedirect(reverse('index:index'))  # set url by appointed URL
    context = {'form': form}
    return render(request, 'new_spot.html', context)

# @login_required
#def createOrder(request, id):
#     if request.method != 'POST':
#
#     # 注文に応じる
#     # いまのユーザーにオーダーをつくって
#     new_order = Order.objects.create()

ParkLot/order/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from .models import *

@login_required
def orderView(request):
    # orders = Order.objects.get(user = )
    # context = {'orders': orders}
    # return render(request, 'order.html', context)
    return render(request, 'order.html')

ParkLot/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm

def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse('index:index'))

def registerView(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # ログインをさせてフロントページに入らせて
            authenticate_user = authenticate(username=new_user.username,
                                             password=request.POST['password1'])
            login(request, authenticate_user)
            return HttpResponseRedirect(reverse('index:index'))
    context = {'form': form}
    return render(request, 'register.html', context)

ParkLot/index/templates/base.html
<p>
    <a href="{% url 'index:index' %}">Front Page</a>
    <a href="{% url 'order:my_order' %}">My Order</a>
    {% if user.is_authenticated %}
        Hello, {{ user.username }}
        <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">register</a>
        <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
</p>
{% block content %} {% endblock content %}

ParkLot/index/templates/index.html
{% extends "base.html" %}
{% block content %}
    <a href="{% url 'maps:gmap' %}">Route</a>
    <br><br>
    <a href="{% url 'maps:new_spot' %}">add spot</a>
    <br><br>
    <a href="{% url 'order:my_order' %}">your order</a>
{% endblock content %}

ParkLot/maps/templates/base.html
<p>
    <a href="{% url 'index:index' %}">Front Page</a>
    <a href="{% url 'order:my_order' %}">My Order</a>
    {% if user.is_authenticated %}
        Hello, {{ user.username }}
        <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">register</a>
        <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
</p>
{% block content %} {% endblock content %}

ParkLot/maps/templates/gmap.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
    <style type="text/css">
        body,html,#container{
            width: 100%;
            height: 100%;
            margin: 0px
        }
    </style>
    <title>车位寻找</title>
</head>
<body>
{#訂正したところ、ご注意ください#}
<p>
    <a href="{% url 'index:index' %}">Front Page</a>
</p>
{#訂正したところ、ご注意ください#}
<div id="container" tabindex="0"></div>
<script src="https://webapi.amap.com/maps?v=1.4.2&key=608d75903d29ad471362f8c58c550daf"></script>
<script type="text/javascript">
    {#var Center = {{ Center|safe }};#}
    var map = new AMap.Map('container', {
        resizeEnable: true,
        {#center:[116.480983, 39.989628],#}
        {#center: Center,#}
        zoom:20
    });
    AMap.plugin('AMap.ToolBar',function(){
        AMap.plugin('AMap.Geolocation', function() {
            var geolocation = new AMap.Geolocation({
                enableHighAccuracy: true,//是否使用高精度定位，默认:true
                timeout: 10000,          //超过10秒后停止定位，默认：5s
                buttonPosition:'RB',    //定位按钮的停靠位置
                buttonOffset: new AMap.Pixel(10, 20),//定位按钮与设置的停靠位置的偏移量，默认：Pixel(10, 20)
                zoomToAccuracy: true,   //定位成功后是否自动调整地图视野到定位点

            });
            map.addControl(geolocation);
            geolocation.getCurrentPosition(function(status,result){
                if(status=='complete'){
                    onComplete(result)
                }else{
                    onError(result)
                }
            });
        });
        //解析定位结果
        function onComplete(data) {
            document.getElementById('status').innerHTML='定位成功'
            var str = [];
            str.push('定位结果：' + data.position);
            str.push('定位类别：' + data.location_type);
            if(data.accuracy){
                str.push('精度：' + data.accuracy + ' 米');
            }//如为IP精确定位结果则没有精度信息
            str.push('是否经过偏移：' + (data.isConverted ? '是' : '否'));
            document.getElementById('result').innerHTML = str.join('<br>');
        }
        //解析定位错误信息
        function onError(data) {
            document.getElementById('status').innerHTML='定位失败'
            document.getElementById('result').innerHTML = '失败原因排查信息:'+data.message;
        }
        {#var toolbar = new AMap.ToolBar();#}
        {#map.addControl(toolbar)#}
    })
</script>
<script type="text/javascript" src="https://webapi.amap.com/demos/js/liteToolbar.js"></script>
</body>
</html>

ParkLot/maps/templates/new_spot.html
{% extends "base.html" %}
{% block content %}
    <p>Add your personal spot:</p>
    <form action="{% url 'maps:new_spot' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add spot</button>
    </form>
{% endblock content %}

ParkLot/maps/templates/scan.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>二维码扫描</title>
    <link rel="stylesheet" href="./css/base.css" />
</head>

<body>
    <menu class="menu" id="menu">
        <nav class="active">二维码生成</nav> |
        <nav>二维码识别</nav>
    </menu>

    <h1 class="h1">二维码</h1>
    <hr />

    <main class="main">
        <aside class="create">
            <input type="text" id="code" value="http://www.muguilin.com" placeholder="请在这里输入要生成的内容！" />
            <input type="button" value="生成" onclick="create()" />
            <div class="qrcode" id="qrcode"></div>
        </aside>
        <aside class="reader">
            <button class="sweep" onclick="sweep()">扫一扫</button>
            <button class="sweep">
                <input type="file" id="file" onchange="upload()" />从相册选择
            </button>
            <div class="imgurl">
                <img id="imgurl"
                    src="https://raw.githubusercontent.com/MuGuiLin/QRCode/master/VueQRCode/src/assets/github.com.png"
                    alt="当前识别的二维码" />
            </div>
            <textarea class="result" id="result" cols="32" rows="6" placeholder="二维码识别结果！"></textarea>
            <canvas class="canvas" id="canvas"></canvas>
        </aside>
    </main>

    <!-- 二维码生成 -->
    <script src="./js/qrcode.js"></script>
    <script>
        const text = document.querySelector('#code');
        const qrcode = new QRCode(document.querySelector('#qrcode'), {
            text: "http://www.muguilin.com",
            width: 300,
            height: 300,
            colorDark: "blue",
            colorLight: "white",
            correctLevel: QRCode.CorrectLevel.H
        });

        // 生成
        function create() {
            qrcode.clear();
            qrcode.makeCode(text.value);
        };
    </script>

    <!-- 二维码识别 -->
    <script src="./js/jimp.js"></script>
    <script src="./js/jsqr.min.js"></script>
    <script src="./js/base.js"></script>
    <script>
        const result = document.querySelector('#result');
        const QrCode = new QrCodeRecognition({
            sweepId: '#canvas',
            uploadId: '#file',
            error: function (err) {
                // 识别错误反馈
                result.value = err;
            },
            seuccess: function (res) {
                // 识别成功反馈
                result.value = res.data;
            }
        });

        // 扫一扫
        function sweep() {
            result.value = '';
            QrCode.sweep();
        };

        // 从相册选择
        function upload() {
            result.value = '';
            QrCode.upload();
        };
    </script>

    <!-- Demo页面交互 -->
    <script>
        const menu = [...document.querySelectorAll('nav')];
        const aside = [...document.querySelectorAll('aside')];
        menu.forEach((nav, n) => {
            nav.onclick = () => {
                aside.forEach((ele, a) => {
                    ele.style.display = 'none';
                    menu[a].classList.remove('active');
                });
                menu[n].classList.add('active');
                aside[n].style.display = 'block';
            }
        });
    </script>
</body>

</html>

ParkLot/order/templates/base.html
<p>
    <a href="{% url 'index:index' %}">Front Page</a>
    <a href="{% url 'order:my_order' %}">My Order</a>
    {% if user.is_authenticated %}
        Hello, {{ user.username }}
        <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">register</a>
        <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
</p>
{% block content %} {% endblock content %}

ParkLot/order/templates/order.html
{% extends "base.html" %}
{% block content %}
    <p>Your Orders</p>
    <ul>
        {% for order in orders %}
            <li>{{ order }}</li>>
        {% empty %}
            <li>No Order has been made yet.</li>
        {% endfor %}
    </ul>
{% endblock content %}

ParkLot/users/templates/base.html
<p>
    <a href="{% url 'index:index' %}">Front Page</a>
    <a href="{% url 'order:my_order' %}">My Order</a>
    {% if user.is_authenticated %}
        Hello, {{ user.username }}
        <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">register</a>
        <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
</p>
{% block content %} {% endblock content %}

ParkLot/users/templates/login.html
{% extends "base.html" %}
{% block content %}
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">log in</button>
{#        隠されたのポストだ、自分のデータを提出したらURLにアクセスする#}
        <input type="hidden" name="next" value="{% url 'index:index' %}" />
    </form>
{% endblock content %}

ParkLot/users/templates/register.html
{% extends "base.html" %}
{% block content %}
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">register</button>
        <input type="hidden" name="next" value="{% url 'index:index' %}" />
    </form>
{% endblock content %}